# Generated by Django 2.0.4 on 2018-04-28 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualuser',
            name='experience',
            field=models.IntegerField(default=0, help_text='experience in months'),
        ),
    ]
